### PR TITLE
Add q-select severity filter

### PR DESCRIPTION
**Pull request by pastalian**
Use q-select for the version selector as well to ensure visual consistency.

Feedback welcome :)

### CODE REVIEW

**Comment by javihernandez** [comment]
Hey @pastalian, thanks for this contribution, I think that having the ability to filter by severity is a great addition.
I only have a little reservation regarding the low contrast color between both "Version" and "Severity" labels with their respective selections. Do you have any ideas about how to solve this? Maybe using a text-color in the labels that produces a higher contrast against the selected option? Or maybe increasing the size of the label a bit?

**Comment by pastalian** [comment]
Hmm, how does this look?
I changed it to use "$warning" (#F2C037) and disabled dense mode to increase the font size (14px → 16px).
The color might stand out a bit too much, but I'm no color expert.

**Comment by sboldyreva** [comment]
@pastalian @javihernandez I love the idea! 
And the increased font looks more readable. I'd like to suggest using colors from the [AlmaLinux brandbook](https://github.com/AlmaLinux/almalinux.org/blob/master/static/branding/AlmaLinux%20BrandBook.pdf) to distinguish the filters:
`#68bc11` and `#e1ad00 `
image

**Comment by pastalian** [comment]
Thanks for the suggestion!

**Review by javihernandez — APPROVED** [review]

**Review by sboldyreva — APPROVED** [review]

**Comment by andrewlukoshko** [comment]
Deployed: https://errata.almalinux.org
Thanks for contribution @pastalian

**Pull request merged**
