### PR TITLE
Add jquery.tablesorter 2.31.3

### PR DESCRIPTION
**Pull request by metalefty**
Required for: https://github.com/AlmaLinux/build-system/issues/98

### CODE REVIEW

**Comment by metalefty** [comment]
This PR just adds one js and one css. It takes no effect until loading in errata HTML so it's safe to merge this alone.

**Review by javihernandez — APPROVED** [review]

**Review by maccelf — APPROVED** [review]

**Comment by metalefty** [comment]
@javihernandez As I mentioned top comment, this PR is required for albs-web-server#632 so MUST be deployed before deploying albs-web-server#632. However, albs-web-server#632 is deployed alone.

**Comment by metalefty** [comment]
I also mentioned in https://github.com/AlmaLinux/albs-web-server/pull/632 this must be merged together.

image

**Comment by metalefty** [comment]
As a result of this is not deployed together,  the errata page is not displayed as intended. [This is an intended display](https://github.com/AlmaLinux/albs-web-server/pull/632#issuecomment-1711312375).

image

**Review by Korulag — APPROVED** [review]

**Pull request merged**
